version: 2

updates:
- package-ecosystem: npm
  directory: "/API"
  schedule:
    interval: daily
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 20
  reviewers:
  - fabrice404
  assignees:
  - fabrice404

- package-ecosystem: npm
  directory: "/ETL"
  schedule:
    interval: daily
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 20
  reviewers:
  - fabrice404
  assignees:
  - fabrice404

- package-ecosystem: npm
  directory: "/UI"
  schedule:
    interval: daily
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 10
  reviewers:
  - fabrice404
  assignees:
  - fabrice404
